content.upgrades.cargoCapacity = content.upgrades.invent({
  name: 'Cargo Capacity',
  levels: [
    {
      bonus: 5,
      cost: {
        'common/carbon': 1,
        'common/hydrogen': 1,
        'common/lithium': 1,
        'common/nitrogen': 1,
        'common/oxygen': 1,
        'common/silicon': 1,
      },
      name: 'Cargo Racks +1',
    },
    {
      bonus: 10,
      cost: {
        'common/carbon': 2,
        'common/hydrogen': 2,
        'common/lithium': 2,
        'common/nitrogen': 2,
        'common/oxygen': 2,
        'common/silicon': 2,
        'metal/aluminum': 1,
        'metal/copper': 1,
        'metal/gold': 1,
        'metal/iron': 1,
        'metal/silver': 1,
      },
      name: 'Cargo Racks +2',
    },
    {
      bonus: 15,
      cost: {
        'common/carbon': 4,
        'common/hydrogen': 4,
        'common/lithium': 4,
        'common/nitrogen': 4,
        'common/oxygen': 4,
        'common/silicon': 4,
        'metal/aluminum': 2,
        'metal/copper': 2,
        'metal/gold': 2,
        'metal/iron': 2,
        'metal/silver': 2,
        'exotic/neodymium': 1,
        'exotic/thorium': 1,
        'exotic/uranium': 1,
      },
      name: 'Cargo Racks +3',
    },
    {
      bonus: 20,
      cost: {
        'common/carbon': 8,
        'common/hydrogen': 8,
        'common/lithium': 8,
        'common/nitrogen': 8,
        'common/oxygen': 8,
        'common/silicon': 8,
        'metal/aluminum': 4,
        'metal/copper': 4,
        'metal/gold': 4,
        'metal/iron': 4,
        'metal/silver': 4,
        'exotic/neodymium': 2,
        'exotic/thorium': 2,
        'exotic/uranium': 2,
        'xenotech/artifact': 1,
      },
      name: 'Cargo Racks +4',
    },
  ],
})
